services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '6969:6969'
    environment:
      - TZ=UTC
      - PORT=6969
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - APP_KEY=iernjEfAeM9bx_oOA_XVcr9FFuoNfGQ2
      - NODE_ENV=production
      - SESSION_DRIVER=cookie
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=app
    depends_on:
      - db
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.app.rule=Host(`localhost`)'

  traefik:
    container_name: traefik
    image: traefik:v3.1
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_data:
